mutation addUser(
  $first_name: String!
  $last_name: String!
  $email: String!
  $password: String!
) {
  insert_user(
    objects: {
      first_name: "tilahun"
      last_name: "tadesse"
      email: "tilahun@gmail.com"
      password: "tita"
    }
  ) {
    returning {
      email
      first_name
      id
      last_name
      password
    }
  }
}
